import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{ts,tsx}", // scan all TS/TSX files
  ],
  theme: {
    extend: {
      colors: {
        // Auto generated by scripts/sync-colors.js
        primary: "#597675",
        primary2: "#79a57c",
        secondary: "#e3336b",
        tertiary: "#ff8800",
        blank: "#fffdfb",
        background: "#0a0a0a",
        background2: "#79a57c",
        text: "#597675",
        textContrast: "#fffdfb",
        foreground: "#ededed",
        colorBackground: "#0a0a0a",
        colorForeground: "#ededed",
        fontSans: "var(--font-geist-sans)",
        fontMono: "var(--font-geist-mono)",
      },
      fontFamily: {
        // 👇 Add CSS variables
        montserrat: ["var(--font-inter)"],
      },
    },
    screens: {
      xs: "480px", // Custom extra-small breakpoint
      sm: "640px", // Default Tailwind breakpoint
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
  },
  plugins: [],
};

export default config;
