name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: ["main"]  # deploy on every push to main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build   # output: "export" handles static generation

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out   # <-- Next.js builds static HTML here

  deploy:
    environment:
      name
